name: hive_data_base
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5
  lottie: ^1.3.0
  path_provider: ^2.0.9
  
  
 

dev_dependencies:
  hive_generator: any
  build_runner: any


  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/

